TeamLocal/Controllers/BusinessController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.EntityFrameworkCore;
using TeamLocal.Data;
using TeamLocal.Models;
using Microsoft.AspNetCore.Authorization;

namespace TeamLocal.Controllers
{
    [Authorize(Roles = "BusinessOwner")]
    public class BusinessController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BusinessController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var list = _context.Businesses.Include(b => b.Category).ToList();
            return View(list);
        }
        // View Page Per Category
        public IActionResult CarServices()
        {
            var list = _context.Businesses.FromSqlRaw("SELECT * FROM Businesses WHERE CategoryID = 1");
            return View(list);
        }
        public IActionResult Cleaning()
        {
            var list = _context.Businesses.FromSqlRaw("SELECT * FROM Businesses WHERE CategoryID = 3");
            return View(list);
        }
        public IActionResult Clothing()
        {
            var list = _context.Businesses.FromSqlRaw("SELECT * FROM Businesses WHERE CategoryID = 4");
            return View(list);
        }

        public IActionResult Food()
        {
            var list = _context.Businesses.FromSqlRaw("SELECT * FROM Businesses WHERE CategoryID = 5");
            return View(list);
        }
        public IActionResult Health()
        {
            var list = _context.Businesses.FromSqlRaw("SELECT * FROM Businesses WHERE CategoryID = 6");
            return View(list);
        }
        public IActionResult HomeImprovement()
        {
            var list = _context.Businesses.FromSqlRaw("SELECT * FROM Businesses WHERE CategoryID = 7");
            return View(list);
        }
        public IActionResult Technology()
        {
            var list = _context.Businesses.FromSqlRaw("SELECT * FROM Businesses WHERE CategoryID = 8");
            return View(list);
        }
        public IActionResult Other()
        {
            var list = _context.Businesses.FromSqlRaw("SELECT * FROM Businesses WHERE CategoryID = 9");
            return View(list);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Business record)
        {
            var selectedCategory = _context.CategoryBusinesses.Where(c => c.CategoryID == record.CategoryID).SingleOrDefault();
            var business = new Business();
            business.BusinessName = record.BusinessName;
            business.BusinessAddress = record.BusinessAddress;
            business.ContactInfo = record.ContactInfo;
            business.Overview = record.Overview;
            business.SocialMedia = record.SocialMedia;
            business.Category = selectedCategory;

            _context.Businesses.Add(business);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var business = _context.Businesses.Where(b => b.BusinessID == id).SingleOrDefault();
            if (business == null)
            {
                return RedirectToAction("Index");
            }

            return View(business);
        }

        [HttpPost]
        public IActionResult Edit(int? id, Business record)
        {
            var business = _context.Businesses.Where(b => b.BusinessID == id).SingleOrDefault();
            var selectedCategory = _context.CategoryBusinesses.Where(c => c.CategoryID == record.CategoryID).SingleOrDefault();
            business.BusinessName = record.BusinessName;
            business.BusinessAddress = record.BusinessAddress;
            business.ContactInfo = record.ContactInfo;
            business.Overview = record.Overview;
            business.SocialMedia = record.SocialMedia;
            business.Category = selectedCategory;

            _context.Businesses.Update(business);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var business = _context.Businesses.Where(b => b.BusinessID == id).SingleOrDefault();
            if (business == null)
            {
                return RedirectToAction("Index");
            }

            _context.Businesses.Remove(business);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }


    }
}

TeamLocal/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.EntityFrameworkCore;
using TeamLocal.Data;
using TeamLocal.Models;

using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace TeamLocal.Controllers
{
    [Authorize(Roles = "BusinessOwner")]
    public class ProductController : Controller
    {

        private readonly ApplicationDbContext _context;

        public ProductController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(int? id)
        {
            if (id == null)
            {
                var listAll = _context.Products.ToList();

                return View(listAll);
            }
            var list = _context.Products.Where(b => b.BusinessID == id).ToList();

            return View(list);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Product record)
        {
            var selectedBusiness = _context.Businesses.Where(b => b.BusinessID == record.BusinessID).SingleOrDefault();
            var product = new Product();

            product.ProductName = record.ProductName;
            product.Description = record.Description;
            product.Price = record.Price;
            product.Business = selectedBusiness;

            //if(ImagePath != null)
            //{
            //    if (ImagePath.Length > 0)
            //    {
            //        var filePath = Path.Combine(Directory.GetCurrentDirectory(),
            //            "wwwroot/images/products", ImagePath.FileName);

            //        using (var stream = new FileStream(filePath, FileMode.Create))
            //        {
            //            ImagePath.CopyTo(stream);
            //        }
            //        product.ImagePath = ImagePath.FileName;
            //    }
            //}

            _context.Products.Add(product);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var product = _context.Products.Where(p => p.ProductID == id).SingleOrDefault();
            if (product == null)
            {
                return RedirectToAction("Index");
            }

            return View(product);
        }

        [HttpPost]
        public IActionResult Edit(int? id, Product record)
        {
            var product = _context.Products.Where(p => p.ProductID == id).SingleOrDefault();
            product.ProductName = record.ProductName;
            product.Description = record.Description;
            product.Price = record.Price;

            _context.Products.Update(product);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var product = _context.Products.Where(p => p.ProductID == id).SingleOrDefault();
            if (product == null)
            {
                return RedirectToAction("Index");
            }

            _context.Products.Remove(product);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

TeamLocal/Views/Business/CarServices.cshtml
@model IEnumerable<TeamLocal.Models.Business>

@{
    ViewData["Title"] = "CarServices";
}

<h1>Car Services</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@foreach (var item in Model)
{
    <div class="list-group">
        <div class="list-group-item">
            <div class="card">
                <div class="card-body col-lg-6">
                    <div class="card-content">
                        <b class="card-title h1 text-warning">
                            @Html.DisplayFor(modelItem => item.BusinessName)
                        </b>
                        <p class="card-text">
                            <b>Rate:</b>
                            @Html.DisplayFor(modelItem => item.Rating)
                        </p>
                        <p>
                            <b>Address:</b>
                            @Html.DisplayFor(modelItem => item.BusinessAddress)
                        </p>
                        <p>
                            <b>Contacts:</b>
                            <i class="text-primary">@Html.DisplayFor(modelItem => item.ContactInfo)</i>
                        </p>
                        <p>
                            <b>Socials:</b>
                            @Html.DisplayFor(modelItem => item.SocialMedia)
                        </p>
                        <p>
                            <b>Overview:</b>
                            @Html.DisplayFor(modelItem => item.Overview)
                        </p>
                    </div>
                </div>

            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-warning btn-lg" data-toggle="modal" data-target="#mymodal">Rate</button>
                <button type="button" class="btn btn-warning btn-lg" data-toggle="modal" data-target="#message">Message</button>
                <a asp-controller="Product" asp-action="Index" asp-route-id="@item.BusinessID" class="btn btn-warning btn-lg">Products</a>
                <a asp-action="Edit" asp-route-id="@item.BusinessID" class="btn btn-warning btn-lg">Edit</a>
                <a asp-action="Delete" asp-route-id="@item.BusinessID" class="btn btn-warning btn-lg">Delete</a>
            </div>
        </div>




    </div>

  

    <div class="modal" id="mymodal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Hi, how did you find our service?</h2>
                </div>
                <div class="modal-body">
                    <div class="star-container">
                        <div class="star-widget">
                            <input type="radio" name="star" id="5" />
                            <label for="5" class="fas fa-star"></label>
                            <input type="radio" name="star" id="4" />
                            <label for="4" class="fas fa-star"></label>
                            <input type="radio" name="star" id="3" />
                            <label for="3" class="fas fa-star"></label>
                            <input type="radio" name="star" id="2" />
                            <label for="2" class="fas fa-star"></label>
                            <input type="radio" name="star" id="1" />
                            <label for="1" class="fas fa-star"></label>
                            <form action="#">
                                <star-header></star-header>
                                <div class="btn">
                                    <button type="submit">Submit</button>
                                </div>
                            </form>
                        </div>

                    </div>

                </div>
            </div>

        </div>

    </div>
}

TeamLocal/Views/Business/Cleaning.cshtml
@model IEnumerable<TeamLocal.Models.Business>

@{
    ViewData["Title"] = "Cleaning";
}

<h1>Cleaning Services</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@foreach (var item in Model)
{
    <div class="list-group">
        <div class="list-group-item">
            <div class="card">
                <div class="card-body col-lg-6">
                    <div class="card-content">
                        <b class="card-title h1 text-warning">
                            @Html.DisplayFor(modelItem => item.BusinessName)
                        </b>
                        <p class="card-text">
                            <b>Rate:</b>
                            @Html.DisplayFor(modelItem => item.Rating)
                        </p>
                        <p>
                            <b>Address:</b>
                            @Html.DisplayFor(modelItem => item.BusinessAddress)
                        </p>
                        <p>
                            <b>Contacts:</b>
                            <i class="text-primary">@Html.DisplayFor(modelItem => item.ContactInfo)</i>
                        </p>
                        <p>
                            <b>Socials:</b>
                            @Html.DisplayFor(modelItem => item.SocialMedia)
                        </p>
                        <p>
                            <b>Overview:</b>
                            @Html.DisplayFor(modelItem => item.Overview)
                        </p>
                    </div>
                </div>

            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-warning btn-lg" data-toggle="modal" data-target="#mymodal">Rate</button>
                <button type="button" class="btn btn-warning btn-lg" data-toggle="modal" data-target="#message">Message</button>
                <a asp-controller="Product" asp-action="Index" asp-route-id="@item.BusinessID" class="btn btn-warning btn-lg">Products</a>
                <a asp-action="Edit" asp-route-id="@item.BusinessID" class="btn btn-warning btn-lg">Edit</a>
                <a asp-action="Delete" asp-route-id="@item.BusinessID" class="btn btn-warning btn-lg">Delete</a>
            </div>
        </div>




    </div>

    <div class="modal" id="mymodal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Hi, how did you find our service?</h2>
                </div>
                <div class="modal-body">
                    <div class="star-container">
                        <div class="star-widget">
                            <input type="radio" name="star" id="5" />
                            <label for="5" class="fas fa-star"></label>
                            <input type="radio" name="star" id="4" />
                            <label for="4" class="fas fa-star"></label>
                            <input type="radio" name="star" id="3" />
                            <label for="3" class="fas fa-star"></label>
                            <input type="radio" name="star" id="2" />
                            <label for="2" class="fas fa-star"></label>
                            <input type="radio" name="star" id="1" />
                            <label for="1" class="fas fa-star"></label>
                            <form action="#">
                                <star-header></star-header>
                                <div class="btn">
                                    <button type="submit">Submit</button>
                                </div>
                            </form>
                        </div>

                    </div>

                </div>
            </div>

        </div>

    </div>
}

TeamLocal/Views/Business/Clothing.cshtml
@model IEnumerable<TeamLocal.Models.Business>

@{
    ViewData["Title"] = "Clothing";
}

<h1>Clothing</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@foreach (var item in Model)
{
    <div class="list-group">
        <div class="list-group-item">
            <div class="card">
                <div class="card-body col-lg-6">
                    <div class="card-content">
                        <b class="card-title h1 text-warning">
                            @Html.DisplayFor(modelItem => item.BusinessName)
                        </b>
                        <p class="card-text">
                            <b>Rate:</b>
                            @Html.DisplayFor(modelItem => item.Rating)
                        </p>
                        <p>
                            <b>Address:</b>
                            @Html.DisplayFor(modelItem => item.BusinessAddress)
                        </p>
                        <p>
                            <b>Contacts:</b>
                            <i class="text-primary">@Html.DisplayFor(modelItem => item.ContactInfo)</i>
                        </p>
                        <p>
                            <b>Socials:</b>
                            @Html.DisplayFor(modelItem => item.SocialMedia)
                        </p>
                        <p>
                            <b>Overview:</b>
                            @Html.DisplayFor(modelItem => item.Overview)
                        </p>
                    </div>
                </div>

            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-warning btn-lg" data-toggle="modal" data-target="#mymodal">Rate</button>
                <button type="button" class="btn btn-warning btn-lg" data-toggle="modal" data-target="#message">Message</button>
                <a asp-controller="Product" asp-action="Index" asp-route-id="@item.BusinessID" class="btn btn-warning btn-lg">Products</a>
                <a asp-action="Edit" asp-route-id="@item.BusinessID" class="btn btn-warning btn-lg">Edit</a>
                <a asp-action="Delete" asp-route-id="@item.BusinessID" class="btn btn-warning btn-lg">Delete</a>
            </div>
        </div>




    </div>

    <div class="modal" id="mymodal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Hi, how did you find our service?</h2>
                </div>
                <div class="modal-body">
                    <div class="star-container">
                        <div class="star-widget">
                            <input type="radio" name="star" id="5" />
                            <label for="5" class="fas fa-star"></label>
                            <input type="radio" name="star" id="4" />
                            <label for="4" class="fas fa-star"></label>
                            <input type="radio" name="star" id="3" />
                            <label for="3" class="fas fa-star"></label>
                            <input type="radio" name="star" id="2" />
                            <label for="2" class="fas fa-star"></label>
                            <input type="radio" name="star" id="1" />
                            <label for="1" class="fas fa-star"></label>
                            <form action="#">
                                <star-header></star-header>
                                <div class="btn">
                                    <button type="submit">Submit</button>
                                </div>
                            </form>
                        </div>

                    </div>

                </div>
            </div>

        </div>

    </div>
}

TeamLocal/Views/Business/Food.cshtml
@model IEnumerable<TeamLocal.Models.Business>

@{
    ViewData["Title"] = "Food";
}

<h1>Food</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@foreach (var item in Model)
{
    <div class="list-group">
        <div class="list-group-item">
            <div class="card">
                <div class="card-body col-lg-6">
                    <div class="card-content">
                        <b class="card-title h1 text-warning">
                            @Html.DisplayFor(modelItem => item.BusinessName)
                        </b>
                        <p class="card-text">
                            <b>Rate:</b>
                            @Html.DisplayFor(modelItem => item.Rating)
                        </p>
                        <p>
                            <b>Address:</b>
                            @Html.DisplayFor(modelItem => item.BusinessAddress)
                        </p>
                        <p>
                            <b>Contacts:</b>
                            <i class="text-primary">@Html.DisplayFor(modelItem => item.ContactInfo)</i>
                        </p>
                        <p>
                            <b>Socials:</b>
                            @Html.DisplayFor(modelItem => item.SocialMedia)
                        </p>
                        <p>
                            <b>Overview:</b>
                            @Html.DisplayFor(modelItem => item.Overview)
                        </p>
                    </div>
                </div>

            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-warning btn-lg" data-toggle="modal" data-target="#mymodal">Rate</button>
                <button type="button" class="btn btn-warning btn-lg" data-toggle="modal" data-target="#message">Message</button>
                <a asp-controller="Product" asp-action="Index" asp-route-id="@item.BusinessID" class="btn btn-warning btn-lg">Products</a>
                <a asp-action="Edit" asp-route-id="@item.BusinessID" class="btn btn-warning btn-lg">Edit</a>
                <a asp-action="Delete" asp-route-id="@item.BusinessID" class="btn btn-warning btn-lg">Delete</a>
            </div>
        </div>




    </div>

    <div class="modal" id="mymodal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Hi, how did you find our service?</h2>
                </div>
                <div class="modal-body">
                    <div class="star-container">
                        <div class="star-widget">
                            <input type="radio" name="star" id="5" />
                            <label for="5" class="fas fa-star"></label>
                            <input type="radio" name="star" id="4" />
                            <label for="4" class="fas fa-star"></label>
                            <input type="radio" name="star" id="3" />
                            <label for="3" class="fas fa-star"></label>
                            <input type="radio" name="star" id="2" />
                            <label for="2" class="fas fa-star"></label>
                            <input type="radio" name="star" id="1" />
                            <label for="1" class="fas fa-star"></label>
                            <form action="#">
                                <star-header></star-header>
                                <div class="btn">
                                    <button type="submit">Submit</button>
                                </div>
                            </form>
                        </div>

                    </div>

                </div>
            </div>

        </div>

    </div>
}

TeamLocal/Views/Business/Health.cshtml
@model IEnumerable<TeamLocal.Models.Business>

@{
    ViewData["Title"] = "Health";
}

<h1>Health</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@foreach (var item in Model)
{
    <div class="list-group">
        <div class="list-group-item">
            <div class="card">
                <div class="card-body col-lg-6">
                    <div class="card-content">
                        <b class="card-title h1 text-warning">
                            @Html.DisplayFor(modelItem => item.BusinessName)
                        </b>
                        <p class="card-text">
                            <b>Rate:</b>
                            @Html.DisplayFor(modelItem => item.Rating)
                        </p>
                        <p>
                            <b>Address:</b>
                            @Html.DisplayFor(modelItem => item.BusinessAddress)
                        </p>
                        <p>
                            <b>Contacts:</b>
                            <i class="text-primary">@Html.DisplayFor(modelItem => item.ContactInfo)</i>
                        </p>
                        <p>
                            <b>Socials:</b>
                            @Html.DisplayFor(modelItem => item.SocialMedia)
                        </p>
                        <p>
                            <b>Overview:</b>
                            @Html.DisplayFor(modelItem => item.Overview)
                        </p>
                    </div>
                </div>

            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-warning btn-lg" data-toggle="modal" data-target="#mymodal">Rate</button>
                <button type="button" class="btn btn-warning btn-lg" data-toggle="modal" data-target="#message">Message</button>
                <a asp-controller="Product" asp-action="Index" asp-route-id="@item.BusinessID" class="btn btn-warning btn-lg">Products</a>
                <a asp-action="Edit" asp-route-id="@item.BusinessID" class="btn btn-warning btn-lg">Edit</a>
                <a asp-action="Delete" asp-route-id="@item.BusinessID" class="btn btn-warning btn-lg">Delete</a>
            </div>
        </div>




    </div>

    <div class="modal" id="mymodal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Hi, how did you find our service?</h2>
                </div>
                <div class="modal-body">
                    <div class="star-container">
                        <div class="star-widget">
                            <input type="radio" name="star" id="5" />
                            <label for="5" class="fas fa-star"></label>
                            <input type="radio" name="star" id="4" />
                            <label for="4" class="fas fa-star"></label>
                            <input type="radio" name="star" id="3" />
                            <label for="3" class="fas fa-star"></label>
                            <input type="radio" name="star" id="2" />
                            <label for="2" class="fas fa-star"></label>
                            <input type="radio" name="star" id="1" />
                            <label for="1" class="fas fa-star"></label>
                            <form action="#">
                                <star-header></star-header>
                                <div class="btn">
                                    <button type="submit">Submit</button>
                                </div>
                            </form>
                        </div>

                    </div>

                </div>
            </div>

        </div>

    </div>
}

TeamLocal/Views/Business/Index.cshtml
@model IEnumerable<TeamLocal.Models.Business>

@{
    ViewData["Title"] = "Index";
}

<ol class="breadcrumb">
    <li><p>View Per Category: &nbsp;</p></li>
    <li class="breadcrumb-item"><a asp-controller="Business" asp-action="CarServices">Car Services</a></li>
    <li class="breadcrumb-item"><a asp-controller="Business" asp-action="Cleaning">Cleaning</a></li>
    <li class="breadcrumb-item"><a asp-controller="Business" asp-action="Clothing">Clothing</a></li>
    <li class="breadcrumb-item"><a asp-controller="Business" asp-action="Food">Food</a></li>
    <li class="breadcrumb-item"><a asp-controller="Business" asp-action="Health">Health</a></li>
    <li class="breadcrumb-item"><a asp-controller="Business" asp-action="HomeImprovement">Home Improvement</a></li>
    <li class="breadcrumb-item"><a asp-controller="Business" asp-action="Technology">Technology</a></li>
    <li class="breadcrumb-item"><a asp-controller="Business" asp-action="Other">Other</a></li>
    
</ol>

<h1>Businesses</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table id="records" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BusinessName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BusinessAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactInfo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Overview)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SocialMedia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody class="table-striped table-hover text-dark">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BusinessName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BusinessAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactInfo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Overview)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SocialMedia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.BusinessID">Edit</a> |
                   
                    <a asp-action="Delete" asp-route-id="@item.BusinessID">Delete</a> |

                    <a class="text-primary" asp-controller="Product" asp-action="Index" asp-route-id="@item.BusinessID">Products</a>
                </td>
            </tr>
        }
    </tbody>
</table>



@section Scripts{
    <script src="~/lib/datatables/js/jquery.dataTables.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.js"></script>
    <script>
            $(document).ready(function () {
                $('#records').DataTable();
            });
    </script>
}